# Generated by Django 3.2.4 on 2021-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/valorantreddit-bc761.appspot.com/o/user_avatar%2Fdefault_avatar.png?alt=media&token=3796a9f0-32f7-48c0-b6d4-fb4e71455fd6'),
        ),
    ]
