# Generated by Django 3.2.4 on 2021-06-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='content',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='reply_comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('rate', models.IntegerField(verbose_name=range(0, 5))),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.viewer')),
            ],
        ),
    ]
