# Generated by Django 3.2.4 on 2021-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210609_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color_code',
            field=models.CharField(default='primary', max_length=20),
        ),
    ]
