# Generated by Django 3.2.4 on 2021-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_topic_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='color_code',
        ),
        migrations.AddField(
            model_name='topic',
            name='background_color_code',
            field=models.CharField(default='007bff', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='font_color_code',
            field=models.CharField(default='ffffff', max_length=20),
        ),
    ]
