# Generated by Django 3.2.4 on 2021-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210610_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='background_color_code',
            field=models.CharField(default='#007bff', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='font_color_code',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
